package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class services_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>Blue Office - Service Page</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<!--\r\n");
      out.write("Template 2036 Blue Office\r\n");
      out.write("http://www.tooplate.com/view/2036-blue-office\r\n");
      out.write("-->\r\n");
      out.write("<link href=\"tooplate_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"subpage\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tooplate_wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"tooplate_sidebar\">\r\n");
      out.write("\t\t\t<div id=\"site_title\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"><span></span></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"home_service\">\r\n");
      out.write("\t\t\t\t<div class=\"home_service_box\">\r\n");
      out.write("\t\t\t\t\t<span class=\"service1\"></span>\r\n");
      out.write("\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">Service One</a>\r\n");
      out.write("\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\tInteger sit amet nulla vitae urna porttitor quis et tellus.\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"home_service_box\">\r\n");
      out.write("\t\t\t\t\t<span class=\"service2\"></span>\r\n");
      out.write("\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">Service Two</a>\r\n");
      out.write("\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\tMorbi lectus erat, tempus ac mattis eu, fringilla id elit.\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"home_service_box\">\r\n");
      out.write("\t\t\t\t\t<span class=\"service3\"></span>\r\n");
      out.write("\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">Service Three</a>\r\n");
      out.write("\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\tNulla quam mi, faucibus non laoreet nec.\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"sidebar_box\">\r\n");
      out.write("\t\t\t\t<h4>Newsletter</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"newsletter_box\">\r\n");
      out.write("\t\t\t\t\t<form action=\"#\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\tPlease enter your email address to subscribe our newsletter.<br />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"newsletter_email\" name=\"newsletter_email\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"newsletter_email\" /> <input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"submit_subscribe\" id=\"submit_subscribe\" value=\"Subscribe\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"cleaner\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"sidebar_box sbb_last\">\r\n");
      out.write("\t\t\t\t<strong>Company Name</strong><br /> 172-168 Curabitur massa ipsum,\r\n");
      out.write("\t\t\t\t<br /> Proin dignissim molestie, 15500<br /> Venenatis ut turpis<br />\r\n");
      out.write("\t\t\t\t<b>Email:</b> <a href=\"mailto:info@yoursite.com\">info@yoursite.com</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- end of sidebar -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"tooplate_main\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"tooplate_menu\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"about.jsp\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"services.jsp\" class=\"current\">Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"gallery.jsp\">Gallery</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end of tooplate_menu -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"content_title_box\">\r\n");
      out.write("\t\t\t\t<h2>Our Services</h2>\r\n");
      out.write("\t\t\t\t<p>Morbi luctus libero non ipsum adipiscing quis sagittis lorem\r\n");
      out.write("\t\t\t\t\teuismod. Quisque vel velit orci, ac vestibulum erat. Aenean sit\r\n");
      out.write("\t\t\t\t\tamet metus ut magna vulputate molestie.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"tooplate_content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"striped-sections\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("<form action=\"saveorgan.jsp\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Name_Title\"> Title </label> <select\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"Name_Title\" name=\"Name.Title\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"\">Please Select</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MR\">Mr</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MRS\">Mrs</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MIS\">Miss</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"DR\">Doctor</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"CLL\">Councillor</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"CAP\">Captain</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"COL\">Colonel</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"EXO\">Executors of</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"LAD\">Lady</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"LOR\">Lord</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"PRO\">Professor</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"REV\">Reverend</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"SIR\">Sir</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"Name.Title\" data-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Name_Forename\"> First name </label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-required=\"This field is required\" id=\"Name_Forename\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmaxlength=\"37\" name=\"fname\" value=\"\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"Name.Forename\" data-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Name_Surname\"> Last name </label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-required=\"This field is required\" id=\"Name_Surname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmaxlength=\"42\" name=\"lname\" value=\"\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"Name.Surname\" data-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Name_OtherName\"> Middle Name (If applicable)\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> <input class=\"form-control\" id=\"Name_OtherName\" maxlength=\"37\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"Name.OtherName\" value=\"\" type=\"text\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"field-validation-valid\" data-valmsg-for=\"Name.OtherName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Name_PreferredName\"> Preferred name </label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"Name_PreferredName\" maxlength=\"37\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"Name.PreferredName\" value=\"\" type=\"text\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"Name.PreferredName\" data-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Address_Postcode\" class=\"block\"> Postcode </label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control postcode\" data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-regex=\"Please enter a valid post code\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-regex-pattern=\"[a-zA-Z]{1,2}[0-9R][0-9a-zA-Z]?\\s?[0-9][^cCiIkKmMoOvV]{2}\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-required=\"This field is required\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"Address_Postcode\" maxlength=\"10\" name=\"Address.Postcode\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"\" type=\"text\"> <input class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"postcode-lookup\" value=\"Find address\" type=\"button\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br> <span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"Address.Postcode\" data-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"lookup-result\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Address_AddressLine1\"> Address Line 1 </label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-required=\"This field is required\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"Address_AddressLine1\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"address\" value=\"\" type=\"text\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"Address.AddressLine1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Address_AddressLine2\"> Address Line 2 </label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"Address_AddressLine2\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"Address.AddressLine2\" value=\"\" type=\"text\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"Address.AddressLine2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Address_AddressLine3\"> Town </label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"Address_AddressLine3\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"Address.AddressLine3\" value=\"\" type=\"text\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"Address.AddressLine3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Address_AddressLine4\"> County </label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"Address_AddressLine4\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"Address.AddressLine4\" value=\"\" type=\"text\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"Address.AddressLine4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Address_AddressLine5\"> Country </label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"Address_AddressLine5\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"Address.AddressLine5\" value=\"\" type=\"text\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"Address.AddressLine5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<fieldset class=\"form-section checkboxes\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<strong class=\"req\">Do you want to donate all organs and\r\n");
      out.write("\t\t\t\t\t\t\t\ttissue?</strong>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display: block;\" id=\"donate-options\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong class=\"req\">Please select which organs and\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttissue you wish to donate:</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6  add-padd right no-padding\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"checkbox\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"btn btn-default btn-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor=\"DonationWishes_DonateKidney\"> Kidney <a title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-question-sign pull-right form-tooltip label-tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trole=\"button\" tabindex=\"-1\" aria-hidden=\"Kidney\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"popover\" data-placement=\"auto right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-trigger=\"focus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-content=\"Your kidneys filter wastes from your blood and convert them to urine. When your kidneys stop working you can develop kidney failure. Harmful wastes and fluids build up in your body and your blood pressure may rise. You can live healthily with one kidney.  \"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label> <input data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-required=\"The Donate Kidney field is required.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif=\"Donate Kidney is required due to DonateAllOrgans being equal to False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentproperty=\"DonateAllOrgans\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentvalue=\"False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-operator=\"EqualTo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"DonationWishes_DonateKidney\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"organs\" value=\"Kidney\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"DonationWishes.DonateKidney\" value=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"hidden\"> <span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"DonationWishes.DonateKidney\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"checkbox\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"btn btn-default btn-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor=\"DonationWishes_DonateHeart\"> Heart <a title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-question-sign pull-right form-tooltip label-tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trole=\"button\" tabindex=\"-1\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"popover\" data-placement=\"auto right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-trigger=\"focus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-content=\"Blood being pumped around your body by your heart carries oxygen and nutrients. Without the heart, your body wouldnât get oxygen.  \"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label> <input data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-required=\"The Donate Heart field is required.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif=\"Donate Heart is required due to DonateAllOrgans being equal to False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentproperty=\"DonateAllOrgans\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentvalue=\"False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-operator=\"EqualTo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"DonationWishes_DonateHeart\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"DonationWishes.DonateHeart\" value=\"Heart\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"organs\" value=\"false\" type=\"hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"DonationWishes.DonateHeart\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"checkbox\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"btn btn-default btn-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor=\"DonationWishes_DonateLiver\"> Liver <a title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-question-sign pull-right form-tooltip label-tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trole=\"button\" tabindex=\"-1\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"popover\" data-placement=\"auto right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-trigger=\"focus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-content=\"Your liver produces bile to clean out your body. If your liver isnât working right, you will begin to feel tired, experience nausea, vomiting, decreased appetite, brown urine, or even jaundice - yellowing in the whites of your eyes.  \"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label> <input data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-required=\"The Donate Liver field is required.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif=\"Donate Liver is required due to DonateAllOrgans being equal to False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentproperty=\"DonateAllOrgans\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentvalue=\"False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-operator=\"EqualTo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"DonationWishes_DonateLiver\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"organs\" value=\"Liver\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"organs\" value=\"false\" type=\"hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"DonationWishes.DonateLiver\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"checkbox\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"btn btn-default btn-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor=\"DonationWishes_DonateSmallBowel\"> Small bowel <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle=\"\" data-original-title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-question-sign pull-right form-tooltip label-tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trole=\"button\" tabindex=\"-1\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"popover\" data-placement=\"auto right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-trigger=\"focus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-content=\"The small bowel (also small intestine) absorbs nutrients and minerals from food we eat. If your small intestine fails, you wouldnât be able to digest food. You would need to get nutrition from an alternative method, such as through a drip into your vein.  \"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label> <input data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-required=\"The Donate Small Bowel field is required.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif=\"Donate Small Bowel is required due to DonateAllOrgans being equal to False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentproperty=\"DonateAllOrgans\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentvalue=\"False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-operator=\"EqualTo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"DonationWishes_DonateSmallBowel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"organs\" value=\"Small bowel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"DonationWishes.DonateSmallBowel\" value=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"hidden\"> <span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"DonationWishes.DonateSmallBowel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6  add-padd left no-padding\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"checkbox\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"btn btn-default btn-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor=\"DonationWishes_DonateCornea\"> Corneas <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle=\"\" data-original-title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-question-sign pull-right form-tooltip label-tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trole=\"button\" tabindex=\"-1\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"popover\" data-placement=\"auto right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-trigger=\"focus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-content=\"The cornea lets light into your eyes, without them you wouldnât be able to see. The gift of sight is precious. Everyday 100 people in the UK start to lose their sight. Almost 2 million people in the UK are living with significant sight loss. Your donation can help someone regain their sight. \"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label> <input data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-required=\"The Donate Cornea field is required.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif=\"Donate Cornea is required due to DonateAllOrgans being equal to False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentproperty=\"DonateAllOrgans\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentvalue=\"False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-operator=\"EqualTo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"DonationWishes_DonateCornea\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"DonationWishes.DonateCornea\" value=\"Corneas\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"organs\" value=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"hidden\"> <span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"DonationWishes.DonateCornea\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"checkbox\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"btn btn-default btn-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor=\"DonationWishes_DonateLungs\"> Lungs <a title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-question-sign pull-right form-tooltip label-tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trole=\"button\" tabindex=\"-1\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"popover\" data-placement=\"auto right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-trigger=\"focus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-content=\"Your lungs supply oxygen to your blood and clear carbon dioxide from your body. Without healthy lungs you couldnât breathe properly.  \"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label> <input data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-required=\"The Donate Lungs field is required.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif=\"Donate Lungs is required due to DonateAllOrgans being equal to False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentproperty=\"DonateAllOrgans\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentvalue=\"False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-operator=\"EqualTo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"DonationWishes_DonateLungs\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"organs\" value=\"Lungs\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"DonationWishes.DonateLungs\" value=\"false\" type=\"hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"DonationWishes.DonateLungs\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"checkbox\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"btn btn-default btn-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor=\"DonationWishes_DonatePancreas\"> Pancreas <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle=\"\" data-original-title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-question-sign pull-right form-tooltip label-tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trole=\"button\" tabindex=\"-1\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"popover\" data-placement=\"auto right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-trigger=\"focus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-content=\"Your pancreas is in your abdomen. It produces insulin to control your blood sugar levels. If your pancreas is not working correctly your blood sugar level rises, which can lead to  diabetes.  \"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label> <input data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-required=\"The Donate Pancreas field is required.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif=\"Donate Pancreas is required due to DonateAllOrgans being equal to False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentproperty=\"DonateAllOrgans\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentvalue=\"False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-operator=\"EqualTo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"DonationWishes_DonatePancreas\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"organs\" value=\"Pancreas\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"DonationWishes.DonatePancreas\" value=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"hidden\"> <span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"DonationWishes.DonatePancreas\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"checkbox\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"btn btn-default btn-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor=\"DonationWishes_DonateTissue\"> Tissue <a title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-question-sign pull-right form-tooltip label-tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trole=\"button\" tabindex=\"-1\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"popover\" data-placement=\"auto right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-trigger=\"focus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-content=\"Tissue is a group of cells that carry out a particular job in your body. Tissue donations such as skin, bone and heart valves save hundreds of lives every year. One tissue donor can enhance the lives of more than 50 people. \"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label> <input data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-required=\"The Donate Tissue field is required.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif=\"Donate Tissue is required due to DonateAllOrgans being equal to False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentproperty=\"DonateAllOrgans\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-dependentvalue=\"False\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-val-requiredif-operator=\"EqualTo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"DonationWishes_DonateTissue\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"organs\" value=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"DonationWishes.DonateTissue\" value=\"Tissue\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"hidden\"> <span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"DonationWishes.DonateTissue\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<fieldset class=\"form-section\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group gender\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Gender\" class=\"req\"> Gender </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"btn btn-default btn-label\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-val=\"true\" data-val-required=\"This field is required\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"Gender\" name=\"gender\" tabindex=\"0\" value=\"MAL\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"radio\"> Male </label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-default btn-label\"> <input id=\"Gender\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"gender\" tabindex=\"0\" value=\"FEM\" type=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tFemale </label> <label class=\"btn btn-default btn-label\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"Gender\" name=\"gender\" tabindex=\"0\" value=\"NKN\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"radio\"> Not known </label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-default btn-label\"> <input id=\"Gender\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"gender\" tabindex=\"0\" value=\"NGI\" type=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tNot Given </label> <label class=\"btn btn-default btn-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"Gender\" name=\"gender\" tabindex=\"0\" value=\"TRA\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"radio\"> Transgender \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"field-validation-valid\" data-valmsg-for=\"Gender\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group dob\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"DateOfBirth\" class=\"block\"> Date of birth </label> <select\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"DateOfBirth_Day\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"DateOfBirth.Day\"><option value=\"\">Day</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"6\">6</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"7\">7</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"8\">8</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"9\">9</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"13\">13</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"14\">14</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15\">15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"16\">16</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"17\">17</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"18\">18</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"19\">19</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20\">20</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"21\">21</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"22\">22</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"23\">23</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"24\">24</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"25\">25</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"26\">26</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"27\">27</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"28\">28</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"29\">29</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"30\">30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"31\">31</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <select class=\"form-control\" id=\"DateOfBirth_Month\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"DateOfBirth.Month\"><option value=\"\">Month</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">January</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">February</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"3\">March</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"4\">April</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"5\">May</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"6\">June</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"7\">July</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"8\">August</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"9\">September</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10\">October</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11\">November</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12\">December</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <select class=\"form-control year\" id=\"DateOfBirth_Year\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"DateOfBirth.Year\"><option value=\"\">Year</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1915\">1915</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1916\">1916</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1917\">1917</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1918\">1918</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1919\">1919</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1920\">1920</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1921\">1921</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1922\">1922</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1923\">1923</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1924\">1924</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1925\">1925</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1926\">1926</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1927\">1927</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1928\">1928</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1929\">1929</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1930\">1930</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1931\">1931</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1932\">1932</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1933\">1933</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1934\">1934</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1935\">1935</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1936\">1936</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1937\">1937</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1938\">1938</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1939\">1939</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1940\">1940</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1941\">1941</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1942\">1942</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1943\">1943</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1944\">1944</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1945\">1945</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1946\">1946</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1947\">1947</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1948\">1948</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1949\">1949</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1950\">1950</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1951\">1951</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1952\">1952</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1953\">1953</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1954\">1954</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1955\">1955</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1956\">1956</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1957\">1957</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1958\">1958</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1959\">1959</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1960\">1960</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1961\">1961</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1962\">1962</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1963\">1963</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1964\">1964</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1965\">1965</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1966\">1966</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1967\">1967</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1968\">1968</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1969\">1969</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1970\">1970</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1971\">1971</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1972\">1972</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1973\">1973</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1974\">1974</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1975\">1975</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1976\">1976</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1977\">1977</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1978\">1978</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1979\">1979</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1980\">1980</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1981\">1981</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1982\">1982</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1983\">1983</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1984\">1984</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1985\">1985</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1986\">1986</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1987\">1987</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1988\">1988</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1989\">1989</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1990\">1990</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1991\">1991</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1992\">1992</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1993\">1993</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1994\">1994</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1995\">1995</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1996\">1996</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1997\">1997</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1998\">1998</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1999\">1999</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2000\">2000</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2001\">2001</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2002\">2002</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2003\">2003</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2004\">2004</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2005\">2005</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2006\">2006</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2007\">2007</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2008\">2008</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2009\">2009</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2010\">2010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2011\">2011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2012\">2012</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2013\">2013</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2014\">2014</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2015\">2015</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"DateOfBirth.Date\" data-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group inline-tooltip\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Ethnicity\"> Ethnicity </label> <select\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"Ethnicity\" name=\"Ethnicity\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"\">Please Select</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"AIN\">Asian or Asian British - Indian</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"APA\">Asian or Asian British - Pakistani</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"ABA\">Asian or Asian British -\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tBangladeshi</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"AOT\">Asian or Asian British - Other</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"BCA\">Black or Black British - Caribbean</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"BAF\">Black or Black British - African</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"BOT\">Black or Black British - Other</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"OTC\">Other - Chinese</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"OTH\">Other</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"NST\">Not Stated</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"NRE\">Not Reported</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"WHB\">White - British</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"WHI\">White - Irish</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"WHO\">White - Other</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MWC\">Mixed - White and Black Caribbean</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MWB\">Mixed - White and Black African</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MWA\">Mixed - White and Asian</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MOT\">Mixed - Other</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"Ethnicity\" data-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a title=\"\" data-original-title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-question-sign pull-right form-tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttabindex=\"-1\" aria-hidden=\"true\" data-toggle=\"popover\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-placement=\"auto right\" data-trigger=\"focus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-content=\"Organ failure can affect anyone, regardless of ethnicity, faith or culture. Our ethnicity can determine which diseases we carry. Youâre more susceptible to certain diseases such as diabetes and hypertension, which may result in organ failure, if youâre from a black, Asian or minority ethnic (BAME) community. Blood and tissue types need to match for a successful transplant; organs from people from the same ethnic background are more likely to be a close match.  1,700 people from BAME communities in the UK are waiting for an organ transplant. Donation rates from these communities are low  â we need more donors. \"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group inline-tooltip\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"Religion\"> Religion </label> <select\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"Religion\" name=\"Religion\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"\">Please Select</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"NON\">No religion</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"PRO\">Christian - Protestant</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"CAT\">Christian - Catholic</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"COT\">Christian - Other</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"BUD\">Buddhist</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"HIN\">Hindu</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"JEW\">Jewish</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MUS\">Muslim</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"SIK\">Sikh</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"OTH\">Other</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"NOT\">Not stated</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <span class=\"field-validation-valid\" data-valmsg-for=\"Religion\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span> <a title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-original-title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-question-sign pull-right form-tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttabindex=\"-1\" aria-hidden=\"true\" data-toggle=\"popover\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-placement=\"auto right\" data-trigger=\"focus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-content=\"All the major religions of the UK support organ donation and transplantation in principle. Talk to your religious leader if you have any doubts. \"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"EmailAddress\"> Email </label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-regex=\"Please enter a valid email address\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-regex-pattern=\"[0-9A-Za-z'\\.\\-_]{1,127}@[0-9A-Za-z'\\.\\-_]{1,127}$\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"EmailAddress\" maxlength=\"50\" name=\"email\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\"> <span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"EmailAddress\" data-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"TelephoneNo\"> Phone </label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-regex=\"Please enter a valid telephone number\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-regex-pattern=\"^[0-9 \\-\\(\\)]{1,20}$\" id=\"TelephoneNo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmaxlength=\"21\" name=\"TelephoneNo\" value=\"\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"TelephoneNo\" data-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"MobileNo\"> Mobile </label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-regex=\"Please enter a valid telephone number\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-regex-pattern=\"^[0-9 \\-\\(\\)]{1,20}$\" id=\"MobileNo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmaxlength=\"21\" name=\"mobile\" value=\"\" type=\"text\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"field-validation-valid\" data-valmsg-for=\"MobileNo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"PreferredContact\"> Preferred form of contact\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> <select class=\"form-control\" id=\"PreferredContact\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"PreferredContact\"><option value=\"\">Please\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tSelect</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"POS\">Post</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"EMA\">Email</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"TEL\">Telephone</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MOB\">Mobile</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <span class=\"field-validation-valid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-for=\"PreferredContact\" data-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"ContactConsent\"> <input data-val=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-val-required=\"The Contact Consent field is required.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"ContactConsent\" name=\"ContactConsent\" value=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"checkbox\"><input name=\"ContactConsent\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"false\" type=\"hidden\"> Please tick this box if\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tyou do not want to receive information about how you can\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfurther support NHS Blood and Transplant save lives. </label> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"field-validation-valid\" data-valmsg-for=\"ContactConsent\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-valmsg-replace=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-section\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"container narrow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input name=\"submitCreate\" class=\"btn btn-info btn-lg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"Submit\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"cleaner\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"cleaner\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end of content -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end of content -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"cleaner\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end of wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tooplate_footer_wrapper\">\r\n");
      out.write("\t\t<div id=\"tooplate_footer\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"index.html\">Home</a> | <a href=\"about.html\">About Us</a> | <a\r\n");
      out.write("\t\t\t\thref=\"services.html\">Services</a> | <a href=\"gallery.html\">Gallery</a>\r\n");
      out.write("\t\t\t| <a href=\"contact.html\">Contact</a> <br />\r\n");
      out.write("\t\t\t<br /> Copyright Â© 2048 <a href=\"#\">Company Name</a> - Design: <a\r\n");
      out.write("\t\t\t\thref=\"http://www.tooplate.com\">tooplate</a>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
